projectId: app-qe6zzRXiLCxUjFfQu4N4GU
appName: testpro
description: This a test project
version: "1.0"
hostName: example.test
clusterURL: default
clusterIPs:
- 190.89.89.0
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: werwer
    containerPort: 2121
  OrderService:
    serviceName: orderservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: werrw
    containerPort: 2121
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    avgReplicas: 3
    minReplicas: 3
    maxReplicas: 3
    dockerImage: werwer
    containerPort: 1212
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
